### Получить всех сотрудников
GET http://localhost:8080/employees
### Создать сотрудника
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "ivan",
  "lastName": "ivanov",
  "department": 1,
  "salary": 1000
}

### Создать сотрудника 2
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Mariya",
  "lastName": "Petrova",
  "department": 2,
  "salary": 3000
}

### Создать сотрудника 3
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Maksim",
  "lastName": "semenov",
  "department": 5,
  "salary": 4500
}

### Создать сотрудника 4
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Petr",
  "lastName": "rodionov",
  "department": 5,
  "salary": 8000
}

### Получить сумму зарплат
GET http://localhost:8080/employees/salary/sum

### Получить сотрудника с минимальной зарплатой
GET http://localhost:8080/employees/salary/min

### Получить сотрудника с максимальной зарплатой
GET http://localhost:8080/employees/salary/max

### Получить сотрудников с зарплатой больше средней
GET http://localhost:8080/employees/high-salary

### Получить коллекцию сотрудников
GET http://localhost:8080/department/employees

### получение сотрудников из департамента
GET http://localhost:8080/department/5/employees

### сумма зарплат по департаменту
GET http://localhost:8080/department/5/salary/sum